<?php

/**
 * @file
 * commerce_fraud main file.
 */

define('COMMERCE_FRAUD_KEY', 'commerce_fraud_count');

/**
 * Implements hook_menu().
 */
function commerce_fraud_menu() {
  $items['admin/commerce/config/fraud'] = array(
    'title' => 'Manage frauds',
    'description' => 'Manages the commerce_fraud caps',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_fraud_admin_settings'),
    'access arguments' => array('administer frauds'),
    'file' => '/includes/commerce_fraud.admin.inc',
  );

  if (module_exists('commerce_kickstart_menus')) {
    $items['admin/commerce/config/fraud']['parent'] = 'admin/commerce/config/advanced-settings';
  }

  return $items;
}

/**
 * Implements hook_permission().
 */
function commerce_fraud_permission() {
  return array(
    'administer frauds' => array(
      'title' => t('Administer frauds caps'),
      'description' => t('Allows users to configure the caps defining frauds.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_help().
 */
function commerce_fraud_help($path) {
  switch ($path) {
    case 'admin/commerce/config/fraud':
      return '<p>' . t('This page lets you define the lower and upper caps for each kind of fraud level.') . '</p>';
  }
}

/**
 * Implements hook_views_api().
 */
function commerce_fraud_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_fraud') . '/includes/views',
  );
}

/**
 * Implements hook_views_data().
 */
function commerce_fraud_views_data() {
  $data['commerce_fraud']['table']['group'] = t('Commerce Fraud');
  $data['commerce_fraud']['table']['join'] = array(
    // Exist in all views.
    '#global' => array(),
  );

  $data['commerce_fraud']['commerce_fraud_level'] = array(
    'title' => t('Commerce Fraud Level'),
    'help' => t('Shows the fraud level.'),
    'field' => array(
      'handler' => 'views_handler_commerce_fraud_level',
    ),
  );

  return $data;
}

/**
 * Implements hook_commerce_order_status_info().
 */
function commerce_fraud_commerce_order_status_info() {
  $order_statuses = array();

  $order_statuses['fraudulent'] = array(
    'name' => 'fraudulent',
    'title' => t('Fraudulent (Canceled)'),
    'state' => 'canceled',
  );

  $order_statuses['high_risk'] = array(
    'name' => 'high_risk',
    'title' => t('High Risk (Pending)'),
    'state' => 'pending',
  );

  return $order_statuses;
}
