<?php

/**
 * @file
 * commerce_fraud main file.
 */

/**
 * Implements hook_menu().
 */
function commerce_fraud_menu() {
  $items['admin/commerce/config/fraud'] = array(
    'title' => 'Manage frauds',
    'description' => 'Manages the commerce_fraud caps',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_fraud_admin_settings'),
    'access arguments' => array('administer frauds'),
    'file' => '/includes/commerce_fraud.admin.inc',
  );

  if (module_exists('commerce_kickstart_menus')) {
    $items['admin/commerce/config/fraud']['parent'] = 'admin/commerce/config/advanced-settings';
  }

  return $items;
}

/**
 * Implements hook_permission().
 */
function commerce_fraud_permission() {
  return array(
    'administer frauds' => array(
      'title' => t('Administer frauds caps'),
      'description' => t('Allows users to configure the caps defining frauds.'),
      'restrict access' => TRUE,
    ),
  );
}
